//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNTrack.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iNTrack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] iNTrack_frmDevSetup {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmDevSetup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmHome {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmHome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmInvLookup {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmInvLookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmItem {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmItem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmItems {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmItems", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmLicense {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmLicense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmLogin {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmLogin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmLookup {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmLookup", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmOptions {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmOptions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmPriceCheck {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmPriceCheck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmPrint {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmPrint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmStockCount {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmStockCount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmTransHeader {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmTransHeader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmTransHeaders {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmTransHeaders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmTransLine {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmTransLine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmTransLines {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmTransLines", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_frmView {
            get {
                object obj = ResourceManager.GetObject("iNTrack_frmView", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_imgManager {
            get {
                object obj = ResourceManager.GetObject("iNTrack_imgManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] iNTrack_Properties_Resources {
            get {
                object obj = ResourceManager.GetObject("iNTrack_Properties_Resources", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
